In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
dfd = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis = 'columns')
dfd

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [ ]:
dfd.fillna(method = 'ffill',inplace = True)
dfd

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female  19.0  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [ ]:
input_n = dfd.drop('Survived', axis = 'columns')
target = dfd.Survived
input_n

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female  19.0  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
input_n['Sex_n'] = le.fit_transform(input_n['Sex'])
input_n.head()

   Pclass     Sex   Age     Fare  Sex_n
0       3    male  22.0   7.2500      1
1       1  female  38.0  71.2833      0
2       3  female  26.0   7.9250      0
3       1  female  35.0  53.1000      0
4       3    male  35.0   8.0500      1

In [ ]:
final = input_n.drop('Sex',axis = 'columns')
final

     Pclass   Age     Fare  Sex_n
0         3  22.0   7.2500      1
1         1  38.0  71.2833      0
2         3  26.0   7.9250      0
3         1  35.0  53.1000      0
4         3  35.0   8.0500      1
..      ...   ...      ...    ...
886       2  27.0  13.0000      1
887       1  19.0  30.0000      0
888       3  19.0  23.4500      0
889       1  26.0  30.0000      1
890       3  32.0   7.7500      1

[891 rows x 4 columns]

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [ ]:
x = final
y = target

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [ ]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
model.score(x_test,y_test)

0.8379888268156425

In [ ]:
model.predict([[2,26,14,1]])